In [32]:
import numpy as np


In [33]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
flat=arr.flatten()

In [35]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
idx=[1,3,5] #Fancy indexing
print(flat[idx])

[2 4 6]


In [37]:
#Boolean masking
mask=arr>5
print(arr[mask])

[6 7 8 9]


In [38]:
#Exercise
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [39]:

float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(int)

print(int_arr)

[1 2 3]


In [41]:
arr3=np.array([1,2,3,4,5,6])
idx=[1,3,5]
print(arr3[idx])


[2 4 6]


In [45]:
arr=np.array([1,2,3,4,5,6,7,8,9])
matrix=arr.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
arr=np.array([3,45,7,66,433,234,67,8,9,898])
mask=arr>50
print(arr[mask])

[ 66 433 234  67 898]
