In [15]:
import numpy as np
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [16]:
print(np.sum(arr3d,axis=0))#sum along rows(down each row)
print(np.sum(arr3d,axis=1))#sum along columns(across each row)


[[ 8 10 12]
 [15 17 19]]
[[ 5  7  9]
 [18 20 22]]


In [17]:
print(arr3d[0:2,1:2])

[[[ 4  5  6]]

 [[11 12 13]]]


In [18]:
print(arr3d.shape)

(2, 2, 3)


In [19]:
print(arr3d[0,1,2])

6


In [20]:
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [22]:
arr3d[:,1]=0
print(arr3d)

[[[1 2 3]
  [0 0 0]]

 [[7 8 9]
  [0 0 0]]]
